### PR TITLE
0.0.4 HD graphics based on Aircraft 1.8

### PR DESCRIPTION
**Pull request by snouz**
Hi Nicolas !
As discussed, I've took the liberty to redo the graphics based on the update I pushed on Aircraft.

Version: 0.0.4
Date: 2021-11-13
  Updated-by:
    - snouz
  Changes:
    - New HD graphics based on Aircraft 1.8, including tech, icon, thumbnail.
    - Fixed ingame changelog.

I also optimized losslessly with pnggauntlet, and included a thumbnail following the style of Aircraft. There's now a low res and high res version of the entity. I've done a tech icon that illustrates what the craft does (with scaffolds and stuff)

If there's something you don't like, don't be afraid ask, even if it's a nitpick!

### CODE REVIEW

**Comment by nicolas-lang** [comment]
Whoo, that was fast.
While it is much better thank before I would like to ask for your opinion at a specific issue:

The sprite sheet I have used was derived from the cargo plane, using simple channel mixing, grayscale conversion and dithering.
It was not pretty but it was the best I could do.
I have used dithering because my skills did not allow to create a greyish-white colored, slightly dirty ~cargo plane~ shuttle which still looked pleasing ( https://de.wikipedia.org/wiki/Datei:Discovery_-_Frontalansicht.jpg )

What is your opinion on the dithered look, are you possibly able to create something from the upscaled blue cargo plane that has a bit more uniform white/ivory/gray -ish colors, creating a more realistic look?
... or would you prefer the slight texture of the dithering?

**Comment by nicolas-lang** [comment]
The tech icon is a very subtle but nice improvement :-)

**Comment by snouz** [comment]
I've used textures for buildings to add some rust and uneven textures and stuff, but there's one problem here, it's that it's an animation, and if there are non-uniform part, it will look like the texture is changing as you rote the entity. I pretty much used the same process as you, I selected the blue, and applied noise to that part, as well as high luminosity, then cranked that contrast to the max (things in space look very contrasty because of the lack of atmosphere, and the light or reflective textures are there to minimize sun absorption.
In my opinion we could give more subtlety by having a no-color on the previously blue texture, and maybe some creamy texture on the outside. I have a mask between the two so I can try something

**Comment by snouz** [comment]
Here's a test
https://imgur.com/iXE6xG0

**Comment by nicolas-lang** [comment]
I would consider it a bit to brown, especially with the edges being that white.

If you have masks available would it be an option to do a 3-layer stack?
- a very light uniform gray a base (maybe #f5f5f0 )
- use the noise as alpha and multiply a slightly darker or lighter secondary gray also with a 3-4% yellow or blue tint
- Add high contrast shadows/countours on top


P.S. (this is me being unfiltered and picky, which i consider the most pragmatic, if you consider any current state as "done" I can  merge right away)

**Comment by snouz** [comment]
WDYT?
Imgur

**Comment by nicolas-lang** [comment]
Whoa very nice I don't think the color theme gets any better without having a 3D model for a re-render!

Since it only is one of the pictures of the sheet I don't have all the information, but to me the shadow at the top aft flap seems a bit funky (=missing), I wouldn't mind if all the angles are as good as this one, it's at least a point for a final qs
image

_I am starting to feel a bit bad for all my nitpicking, It is really appreciated what you did with the model!_

**Comment by nicolas-lang** [comment]
very nice! ... everything ready for release from your side ?

**Comment by snouz** [comment]
The thing with the shadow is that i manually removed the fire of the engine from the animation, but I kept the reflected light. I might add it as light later, so in the night it's clear that the rear is bursting. Also, smoke was replace by a light trail.

Anyway, yes, I think the result is ready, except if you have anything to add?

**Pull request merged**
